### ISSUE TITLE
Can not import (Gradle)

### ISSUE THREAD

**Issue by ismaiI1** [aerdy/Viger-PDF#12]
I got this error : 
`Failed to resolve: com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:-SNAPSHOT`

I add `maven { url 'https://jitpack.io' }` to root build.gradle but can not import. What should i do?

**Comment by vishalandroid123** [comment]
I got same this error :
Failed to resolve: com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:-SNAPSHOT

I add maven { url 'https://jitpack.io' } to root build.gradle but can not import. What should i do?

**Comment by osamasaeed** [comment]
I also got same error:
Failed to resolve: com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:-SNAPSHOT

I add maven { url 'https://jitpack.io' } to root build.gradle but can not import. What should i do?

**Comment by joseAugustoCR** [comment]
try this:
compile 'com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:1.2'
