### ISSUE TITLE
Cannot add to my Project

### ISSUE THREAD

**Issue by iammannan** [aerdy/Viger-PDF#3]
When I add to my Project ...
`
Error:Module` 'com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:-SNAPSHOT' `depends on one or more Android Libraries but is a jar

Please provide the solution guys..

**Comment by aerdy** [comment]
you have to entry 

repositories {
        jcenter()
        maven { url 'https://jitpack.io' }
}

**Comment by bboydflo** [comment]
@aerdy I am having the same issue and that won't help :(

**Comment by iammannan** [comment]
Yes that not work.
Pls suggested any othr

**Comment by aerdy** [comment]
ok.. clone project and open modul your project

**Comment by aerdy** [comment]
compile 'com.github.aerdy.Android-Viger_View_Pager_PDF_OpenSource:PDFVigerLib:1.1'

**Comment by iammannan** [comment]
![screenshot 44](https://cloud.githubusercontent.com/assets/22405792/24070353/d02639cc-0be1-11e7-8a4b-e8f2688b6280.png)

**Comment by aerdy** [comment]
sorry all. please clone project and import modul viger your project..

because jitpack profile me limit project. 
I will soon migrate to the server itself

**# I email it to all if the server repo is ready**

**Comment by bboydflo** [comment]
@aerdy thanks!

**Comment by aerdy** [comment]
Check your email  ALL...tutorial build repository your project and supp rxandroid version 1.2

**Comment by aerdy** [comment]
Viger Tutorial

1. Add Depencities root gradle

​- Root Gradle project add line code :
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        **maven { url 'https://jitpack.io' }**
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
- Secondary Gradle add line code

apply plugin: 'com.android.application'

android {
    compileSdkVersion 24
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.example.vim.myapplication"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:24.2.1'
    compile 'com.android.support:design:24.2.1'
    testCompile 'junit:junit:4.12'
    **compile 'com.github.aerdy:Android-Viger_View_Pager_PDF_OpenSource:1.2'**
}
