### ISSUE TITLE
"java.lang.IllegalArgumentException: pointerIndex out of range" When trying to zoom-out.

### ISSUE THREAD

**Issue by ahamadanees** [aerdy/Viger-PDF#4]
VigerPdf is my favorite because it is very lite-weight and supports older versions of android. But here is an issue, app is crashing and "java.lang.IllegalArgumentException: pointerIndex out of range" is thrown sometimes when i try to zoom-out the page. Here is the logcat.

`05-01 11:59:13.561 29070-29184/epicsoft.mymgu D/PdfDroid: doing the rendering... 05-01 11:59:13.929 29070-29184/epicsoft.mymgu D/PdfDroid: Converting image buffer pixel order 05-01 11:59:13.963 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView.nativeCreateView() done 05-01 11:59:14.000 29070-29184/epicsoft.mymgu D/PdfDroid: PdfPage.nativeOpenPage(): return handle = 0xb81f70a0 05-01 11:59:14.001 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView(0xa3dfd1ec).nativeCreateView(0xb80761e8, 0xb81f70a0) 05-01 11:59:14.001 29070-29184/epicsoft.mymgu D/PdfDroid: Matrix: 1.000000 0.000000 0.000000 -1.000000 0.000000 842.000000 05-01 11:59:14.001 29070-29184/epicsoft.mymgu D/PdfDroid: Viewbox: 0 0 595 842 05-01 11:59:14.001 29070-29184/epicsoft.mymgu D/PdfDroid: doing the rendering... 05-01 11:59:14.378 29070-29184/epicsoft.mymgu D/PdfDroid: Converting image buffer pixel order 05-01 11:59:14.410 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView.nativeCreateView() done 05-01 11:59:14.449 29070-29184/epicsoft.mymgu D/PdfDroid: PdfPage.nativeOpenPage(): return handle = 0xb812c6b0 05-01 11:59:14.450 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView(0xa3dfd1ec).nativeCreateView(0xb80761e8, 0xb812c6b0) 05-01 11:59:14.450 29070-29184/epicsoft.mymgu D/PdfDroid: Matrix: 1.000000 0.000000 0.000000 -1.000000 0.000000 842.000000 05-01 11:59:14.450 29070-29184/epicsoft.mymgu D/PdfDroid: Viewbox: 0 0 595 842 05-01 11:59:14.450 29070-29184/epicsoft.mymgu D/PdfDroid: doing the rendering... 05-01 11:59:14.782 29070-29184/epicsoft.mymgu D/PdfDroid: Converting image buffer pixel order 05-01 11:59:14.810 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView.nativeCreateView() done 05-01 11:59:14.840 29070-29184/epicsoft.mymgu D/PdfDroid: PdfPage.nativeOpenPage(): return handle = 0xb8174cb0 05-01 11:59:14.841 29070-29184/epicsoft.mymgu D/PdfDroid: PdfView(0xa3dfd1ec).nativeCreateView(0xb80761e8, 0xb8174cb0) 05-01 11:59:14.841 29070-29184/epicsoft.mymgu D/PdfDroid: Matrix: 1.000000 0.000000 0.000000 -1.000000 0.000000 842.000000 05-01 11:59:14.841 29070-29184/epicsoft.mymgu D/PdfDroid: Viewbox: 0 0 595 842 05-01 11:59:14.841 29070-29184/epicsoft.mymgu D/PdfDroid: doing the rendering... 05-01 11:59:14.941 29070-29070/epicsoft.mymgu E/InputEventReceiver: Exception dispatching input event. 05-01 11:59:14.942 29070-29070/epicsoft.mymgu D/AndroidRuntime: Shutting down VM 05-01 11:59:14.947 29070-29070/epicsoft.mymgu E/AndroidRuntime: FATAL EXCEPTION: main Process: epicsoft.mymgu, PID: 29070 java.lang.IllegalArgumentException: pointerIndex out of range at android.view.MotionEvent.nativeGetAxisValue(Native Method) at android.view.MotionEvent.getX(MotionEvent.java:2014) at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2092) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1960) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2407) at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2106) at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2369) at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1719) at android.app.Activity.dispatchTouchEvent(Activity.java:2752) at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:71) at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2330) at android.view.View.dispatchPointerEvent(View.java:8671) at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4193) at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4059) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623) at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3740) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631) at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3797) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604) at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3657) at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3623) at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3631) at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3604) at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5912) at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5851) at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5822) at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6002) at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192) at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method) at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183) at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5973) at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6025) at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767) at android.view.Choreographer.doCallbacks(Choreographer.java:580) at android.view.Choreographer.doFrame(Choreographer.java:548) at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753) at android.os.Handler.handleCallback(Handler.java:739) at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:135) at android.app.ActivityThread.main(ActivityThread.java:5343) at java.lang.reflect.Method.inv`

**Comment by aerdy** [comment]
Thank you for sending me an email of his issue. 2 days I will do fixing

**Comment by aerdy** [comment]
Done...

add view pager zoom from library..

<com.necistudio.vigerpdf.utils.ViewPagerZoom
        android:id="@+id/viewPager"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

outoffmemory done.

**Comment by ahamadanees** [comment]
Zooming is fixed. But page transitions not working now.

**Comment by ahamadanees** [comment]
Well done bro. Keep up the good work

**Comment by aerdy** [comment]
ty bro...

**Comment by iammannan** [comment]
I have a doubt.Github is an open source .. But how you make money using that open source project

**Comment by iammannan** [comment]
Like a social activity???

**Comment by aerdy** [comment]
We do not have income from the project, but usually there are some companies that donate to us

**Comment by iammannan** [comment]
I am having some idea to create a library... But I don't know to how to
create the library...Please suggest the tutorials.. Thanks in advance
